services:
  jenkins:
    image: jenkins/jenkins:lts-jdk21
    container_name: jankinshost
    restart: on-failure
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - D:/jenkins/jenkins_home:/var/jenkins_home
